Feature/DEV-12 connect sidebar nav and user menu with router
savelievamareena/cv-final pull request #14
Opened 2024-06-03 12:58 UTC by savelievamareena

2024-06-03 14:09 UTC, shev7 requested changes

2024-06-03 14:09 UTC, shev7 commented on src/modules/header/components/navigation/navigation.tsx
> +    }
this can be effectively accoplished with NavLink component

2024-06-03 14:09 UTC, shev7 commented on src/modules/header/header.tsx
> +import getUserNameToDisplay from "src/helpers/user/getUserNameToDisplay.ts";
as I see everywhere in the app named exports are used, why are you using default export here?

2024-06-03 14:09 UTC, shev7 commented on src/modules/header/header.tsx
> +    }, [user]);
you already have this user state inside of user variable returned from useAuthUser, no need to create a separate state

2024-06-03 14:09 UTC, shev7 commented on src/modules/header/header.tsx
>                  <Flex gap={"middle"}>
```suggestion
                <Flex gap="middle">
```

2024-06-03 14:09 UTC, shev7 commented on src/modules/header/languages-select/languages-select.tsx
> +    const [language, setLanguage] = useState(langDefaultUppercase);
```suggestion
    const [language, setLanguage] = useState(Languages.En.toUpperCase());
```

2024-06-03 14:09 UTC, shev7 commented on src/modules/header/user-dropdown-menu/user-dropdown-menu.tsx
> +    if (userId) {
```suggestion
    let userProfileUrl = "";
    
    if (userId) {
```

2024-06-03 15:15 UTC, shev7 requested changes

2024-06-03 15:15 UTC, shev7 commented on src/modules/header/user-dropdown-menu/user-dropdown-menu.tsx
> +    function handleLogout() {
Somewhere you are using arrow functions, somewhere function declaration, please choose one style for functions in team, for example to use arrow functions only and add eslint rule for that

2024-06-03 15:40 UTC, shev7 approved these changes

2024-06-03 15:54 UTC, shev7 approved these changes

2024-06-03 15:54 UTC, shev7 commented on src/modules/header/components/navigation/navigation.tsx
> +import { routes } from "@/router/constants.ts";
```suggestion
import { routes } from "@/router/constants";
```

2024-06-04 10:28 UTC, RC-3222 approved these changes
Also maybe not really related to this exact PR (but to header module in general), but is there a reason for you to prefer using px for font-size (and for most other cases) over some relative units like rem/em?

2024-06-04 10:36 UTC, shev7 commented
> Also maybe not really related to this exact PR (but to header module in general), but is there a reason for you to prefer using px for font-size (and for most other cases) over some relative units like rem/em?

Good catch, remember our discussion about what units needs to be used in each case

2024-06-04 11:33 UTC, savelievamareena commented
> > Also maybe not really related to this exact PR (but to header module in general), but is there a reason for you to prefer using px for font-size (and for most other cases) over some relative units like rem/em?
> 
> Good catch, remember our discussion about what units needs to be used in each case

Agree, I have changed px to rems for font-size and gaps

2024-06-04 13:16 UTC, AAKlimkov approved these changes

2024-06-04 13:34 UTC, merged