Feature/DEV-22 languages page
savelievamareena/cv-final pull request #23
Opened 2024-06-11 08:13 UTC by AAKlimkov

add languages page

2024-06-11 10:06 UTC, shev7 requested changes
same issues as with previous PRs

2024-06-11 11:10 UTC, AAKlimkov commented
1. Added export of languageList
2. Remove unused fragment in languageList
3. pass initialValues to the form in languageDialog
4. Remove unused interface in languageList
5. move columnConfigs from languageList component

2024-06-12 06:33 UTC, shev7 approved these changes

2024-06-12 06:33 UTC, shev7 commented on src/modules/CVs/components/details/details.tsx
> +import CvDetailsForm from "@/modules/cvs/components/cv-details-form/cv-details-form.tsx";
```suggestion
import CvDetailsForm from "@/modules/cvs/components/cv-details-form/cv-details-form";
```

2024-06-12 06:33 UTC, shev7 commented on src/modules/languages/shemas/language.ts
> +    const iso2Message = { message: i18n.t("fieldErrors.nameRequired") };
why key is `nameRequired` if its iso2Message

2024-06-12 06:33 UTC, shev7 commented on src/modules/languages/ui/languages-dialog.tsx
> +    initialValues: { language: string; native_name: string; iso2: string };
this type is the same as `FormData` interface above

```suggestion
    initialValues: FormData;
```

2024-06-12 06:33 UTC, shev7 commented on src/modules/languages/ui/languages-list.tsx
> +import { useAddLanguage } from "./languages-dialog";
if you are using this dialog to both create and update it should be named as useLanguageDialog or something like that, not addLanguage

2024-06-12 08:21 UTC, savelievamareena approved these changes

2024-06-12 08:24 UTC, RC-3222 approved these changes

2024-06-12 08:26 UTC, merged