Feature/DEV-33 positions page
savelievamareena/cv-final pull request #24
Opened 2024-06-11 08:37 UTC by AAKlimkov

add positions page

2024-06-11 10:06 UTC, shev7 requested changes

2024-06-11 10:06 UTC, shev7 commented on src/modules/positions/ui/positions-dialog.tsx
> +    initialValues: { position: string };
You have type for this, use FormData interface

2024-06-11 10:06 UTC, shev7 commented on src/modules/positions/ui/positions-dialog.tsx
> +    const { position } = initialValues;
can't you just pass initialValues to the form, no need to destructure

2024-06-11 10:06 UTC, shev7 commented on src/modules/positions/ui/positions-list.tsx
> +}
this interface is not needed

2024-06-11 10:06 UTC, shev7 commented on src/modules/positions/ui/positions-list.tsx
> +}
you have it type correctly inside of dialog

2024-06-11 10:06 UTC, shev7 commented on src/modules/positions/ui/positions-list.tsx
> +    const columnConfigs: ColumnConfig<Position>[] = [{ name: "name", isSorted: true }];
move out of component

2024-06-11 10:06 UTC, shev7 commented on src/modules/positions/ui/positions-list.tsx
> +        </>
```suggestion
            <ListTemplate
                pageName={t("positions.positions")}
                onButtonClick={openPosition}
                menuProps={menuProps}
                columnConfigs={columnConfigs}
                searchQuery={searchQuery}
                displayData={positions}
                loading={loading}
                setSearchQuery={setSearchQuery}
            />
```

2024-06-11 10:06 UTC, shev7 commented on src/pages/positions/positions.page.tsx
> +import PositionsList from "@/modules/positions/ui/positions-list";
i thought you arranged with guys about named exports, they much better

2024-06-11 11:20 UTC, AAKlimkov commented
1. Added export of SkillsList
2. Remove unused fragment in skill List
3. pass initialValues to the form in skill Dialog
4. Remove unused interface in skill List
5. move columnConfigs from languageList component

2024-06-11 11:21 UTC, AAKlimkov commented on src/pages/positions/positions.page.tsx
> +import PositionsList from "@/modules/positions/ui/positions-list";
we decide to used default to components and named no other exports

2024-06-12 10:42 UTC, RC-3222 commented on src/modules/positions/ui/positions-list.tsx
> +import { usePositionCreate, usePositionDelete, usePositionsQuery, usePositionUpdate } from "../api";
since usePositionsQuery is now part of common API (also needed in profile), probably should replace this with the global one

2024-06-12 10:43 UTC, RC-3222 approved these changes

2024-06-13 10:04 UTC, shev7 approved these changes

2024-06-13 10:04 UTC, shev7 commented on src/modules/positions/ui/positions-dialog.tsx
> +const PositionDialog = ({ title, onConfirm, onClose, initialValues }: PositionDialogProps) => {
```suggestion
}

const PositionDialog = ({ title, onConfirm, onClose, initialValues }: PositionDialogProps) => {
```

2024-06-13 10:04 UTC, shev7 commented on src/modules/positions/ui/positions-dialog.tsx
> +interface PositionDialogProps {
```suggestion
}

interface PositionDialogProps {
```

2024-06-13 11:11 UTC, savelievamareena approved these changes

2024-06-13 12:54 UTC, merged