Feature/DEV-34 add skills page
savelievamareena/cv-final pull request #25
Opened 2024-06-11 09:36 UTC by AAKlimkov

![image](https://github.com/savelievamareena/cv-final/assets/70685916/2d3c5118-f9a5-445c-9cb7-d8ad934491b4)

2024-06-11 10:02 UTC, shev7 requested changes

2024-06-11 10:02 UTC, shev7 commented on src/modules/skills/ui/skills-dialog.tsx
> +    const selectOptions = convertToSelectOptions(skillCategories);
create some kind of helper, this might be used in other forms

2024-06-11 10:02 UTC, shev7 commented on src/modules/skills/ui/skills-list.tsx
> +        </>
```suggestion
            <ListTemplate
                pageName={t("skills.skill")}
                onButtonClick={openSkill}
                menuProps={menuProps}
                columnConfigs={columnConfigs}
                searchQuery={searchQuery}
                displayData={skills}
                loading={loading}
                setSearchQuery={setSearchQuery}
            />
```

2024-06-11 10:02 UTC, shev7 commented on src/modules/skills/ui/skills-list.tsx
>      ];
everything not related to rendering should be mopved out of component

2024-06-11 10:02 UTC, shev7 commented on src/modules/skills/ui/skills-list.tsx
> +}
I saw the same interface in dialog you don't even need it here

2024-06-11 11:22 UTC, AAKlimkov commented
1.Added export of SkillsList
2.Remove unused fragment in skill List
3.pass initialValues to the form in skill Dialog
4. Remove unused interface in skill List
5. move columnConfigs from languageList component

2024-06-13 13:44 UTC, RC-3222 approved these changes

2024-06-14 12:15 UTC, shev7 approved these changes

2024-06-14 13:08 UTC, savelievamareena approved these changes

2024-06-15 09:28 UTC, merged