Feature/DEV-22-user-languages-page
savelievamareena/cv-final pull request #34
Opened 2024-06-21 11:32 UTC by RC-3222

Basic user languages page functionality
![image](https://github.com/savelievamareena/cv-final/assets/99599598/a918f1a8-6ee3-4377-82cd-1e8967bdd1a6)

![image](https://github.com/savelievamareena/cv-final/assets/99599598/21ac1499-8d88-4f35-a77d-c9e276d6c49a)
![image](https://github.com/savelievamareena/cv-final/assets/99599598/9dd9faed-7b77-4564-9877-70e2396fc485)

![image](https://github.com/savelievamareena/cv-final/assets/99599598/ae16c6cc-7195-4ed2-9226-1440e847b0cd)

2024-06-24 10:18 UTC, shev7 requested changes

2024-06-24 10:18 UTC, shev7 commented on src/modules/users/components/languages-dialog/languages-dialog.tsx
> +    const [deleteMutation, { loading: deleteLoading }] = useDeleteUserLanguage();
put all api hooks to the top

2024-06-24 10:18 UTC, shev7 commented on src/modules/users/components/languages-dialog/languages-dialog.tsx
> +    };
use onCompleted callback as  prop of deleteMutation

2024-06-24 10:18 UTC, shev7 commented on src/modules/users/components/languages-list/item/item.tsx
> +interface LanguagesListItem {
```suggestion
interface LanguagesListItemProps {
```

2024-06-24 10:18 UTC, shev7 commented on src/modules/users/components/languages-list/languages-list.tsx
> +const LanguagesList = ({ userId, canEdit }: SkillProps) => {
Component
ComponentProps

follow this prop naming convention

2024-06-24 10:18 UTC, shev7 commented on src/modules/users/components/languages-list/languages-list.tsx
> +    );
memoization is not even needed here cause you passing this callback to simple button component

2024-06-24 10:18 UTC, shev7 commented on src/modules/users/components/languages-list/languages-list.tsx
> +            ) : null}
```suggestion
            {canEdit && (
                <Button size={"large"} type="text" onClick={addLanguage}>
                    <PlusOutlined />
                    {t("languages.addLanguage")}
                </Button>
            ) }
```

avoid using ternaries

2024-06-24 12:14 UTC, RC-3222 commented on src/modules/users/components/languages-dialog/languages-dialog.tsx
> +    const [deleteMutation, { loading: deleteLoading }] = useDeleteUserLanguage();
fixed

2024-06-24 12:14 UTC, RC-3222 commented on src/modules/users/components/languages-dialog/languages-dialog.tsx
> +    };
fixed

2024-06-24 12:19 UTC, RC-3222 commented on src/modules/users/components/languages-list/item/item.tsx
> +interface LanguagesListItem {
fixed

2024-06-24 12:19 UTC, RC-3222 commented on src/modules/users/components/languages-list/languages-list.tsx
> +const LanguagesList = ({ userId, canEdit }: SkillProps) => {
fixed

2024-06-24 12:20 UTC, RC-3222 commented on src/modules/users/components/languages-list/languages-list.tsx
> +    );
fixed

2024-06-24 12:20 UTC, RC-3222 commented on src/modules/users/components/languages-list/languages-list.tsx
> +            ) : null}
fixed

2024-06-25 11:41 UTC, shev7 approved these changes

2024-06-27 09:45 UTC, AAKlimkov approved these changes

2024-06-27 10:12 UTC, savelievamareena approved these changes

2024-06-27 10:15 UTC, merged