Feature/dev 42 settings page
savelievamareena/cv-final pull request #40
Opened 2024-06-25 12:06 UTC by RC-3222

Added "Settings" page
![image](https://github.com/savelievamareena/cv-final/assets/99599598/d108f49a-08a4-4655-b797-69f3420f8162)
![image](https://github.com/savelievamareena/cv-final/assets/99599598/1798e8cb-a0f2-4f43-9e46-f687298e1565)

Device theme synchronisation if "Device settings" option selected (it is the default)
![image](https://github.com/savelievamareena/cv-final/assets/99599598/cfeff0dc-aa5f-4cd3-9f09-a220ef028975)
![image](https://github.com/savelievamareena/cv-final/assets/99599598/78cf2515-1a08-474c-b4ad-6c90e90185ba)

![image](https://github.com/savelievamareena/cv-final/assets/99599598/28dda975-a6a6-447d-9444-bef462ea75c6)
![image](https://github.com/savelievamareena/cv-final/assets/99599598/a20e61fe-4b41-48db-b666-1da3d77d5e9d)

2024-06-28 11:53 UTC, shev7 requested changes

2024-06-28 11:53 UTC, shev7 commented on src/modules/settings/components/lang-select/lang-select.tsx
> +            { label: "Русский", value: Languages.Ru },
shouldn't labels be taken from translations?

2024-06-28 11:53 UTC, shev7 commented on src/modules/settings/components/theme-select/theme-select.tsx
> +            { label: t("settings.themeSelect.options.light"), value: "light" },
use enum for value

2024-06-28 11:53 UTC, shev7 commented on src/services/theme-service/theme-service.hooks.ts
> +export const useIsDarkAppTheme = () => useReactiveVar(themeService.isDarkScheme);
useIsDarkTheme is bad name for this hook, this should be something like useTheme and should return current theme, and optionally you can return values like isDark, isLight, isDefault for convenience,
cause you might have more themes

2024-06-28 11:53 UTC, shev7 commented on src/services/theme-service/theme-service.hooks.ts
> +        if (themePref !== "default") return;
use value from enum

2024-06-28 11:53 UTC, shev7 commented on src/services/theme-service/theme-service.hooks.ts
> +            else themeService.setTheme("light");
values from enum

2024-06-28 11:53 UTC, shev7 commented on src/services/theme-service/theme-service.hooks.ts
> +    const themePref = useAppThemePref();
not clear what is pref here, try to think about more descriptive name

2024-06-28 11:53 UTC, shev7 commented on src/services/theme-service/theme-service.ts
> +    isDarkScheme = makeVar<boolean>(false);
separate state for isDark is not needed

2024-06-28 12:15 UTC, RC-3222 commented on src/modules/settings/components/lang-select/lang-select.tsx
> +            { label: "Русский", value: Languages.Ru },
no (not according to the initial requirments/example, at least)
![image](https://github.com/savelievamareena/cv-final/assets/99599598/a053815d-fc69-4464-b0b8-d71fa5f13ae7)

2024-06-28 13:14 UTC, RC-3222 commented on src/services/theme-service/theme-service.hooks.ts
> +export const useIsDarkAppTheme = () => useReactiveVar(themeService.isDarkScheme);
refactored (isDark is now part of custom AppThemeConfig type (based on standard ThemeConfig type from antd) and is defined for each exiting theme separately) (there is also a custom object(hash) that uses ThemePreference enum as keys and theme configs as values. with the default dark & light themes specified)

2024-06-28 13:15 UTC, RC-3222 commented on src/modules/settings/components/theme-select/theme-select.tsx
> +            { label: t("settings.themeSelect.options.light"), value: "light" },
fixed

2024-06-28 13:15 UTC, RC-3222 commented on src/services/theme-service/theme-service.hooks.ts
> +        if (themePref !== "default") return;
fixed

2024-06-28 13:15 UTC, RC-3222 commented on src/services/theme-service/theme-service.hooks.ts
> +            else themeService.setTheme("light");
fixed

2024-06-28 13:15 UTC, RC-3222 commented on src/services/theme-service/theme-service.ts
> +    isDarkScheme = makeVar<boolean>(false);
fixed

2024-06-28 13:18 UTC, RC-3222 commented on src/services/theme-service/theme-service.hooks.ts
> +    const themePref = useAppThemePref();
hope that `userThemePreference` would be clearer than this

2024-07-01 13:25 UTC, savelievamareena commented on package.json
> +        "lint:fix": "eslint --fix --ext ts,tsx --report-unused-disable-directives --max-warnings 0 ./src",
Egor removed ./src so that the pre-commit linter only checks files that have been changed, not the entire project

2024-07-02 08:16 UTC, shev7 approved these changes

2024-07-02 08:16 UTC, shev7 commented on src/modules/settings/components/lang-select/lang-select.tsx
> +            { label: "Русский", value: Languages.Ru },
I mean that you should put this to translations and keep values the same for all languages, it is more consistent when you have all text in your rendering used as t()

2024-07-02 08:16 UTC, shev7 commented on src/services/theme-service/themes/light.ts
> +    isDark: false,
do you really need this?

2024-07-02 08:16 UTC, shev7 commented on src/services/theme-service/themes/light.ts
> +    isDark: false,
as I already said you should tie to isDark isLight, you might have more that 2 themes, and rely on boolean flag for theme is not correct

2024-07-02 09:43 UTC, RC-3222 commented on src/modules/settings/components/lang-select/lang-select.tsx
> +            { label: "Русский", value: Languages.Ru },
moved

2024-07-02 09:45 UTC, RC-3222 commented on src/services/theme-service/themes/light.ts
> +    isDark: false,
replaced boolean flags with theme names (tags)

2024-07-03 09:51 UTC, AAKlimkov approved these changes

2024-07-03 14:42 UTC, merged