feat: add basic routing setup
savelievamareena/cv-final pull request #7
Opened 2024-05-26 19:40 UTC by RC-3222

Basic setup for all (currently known) app routes

2024-05-27 06:13 UTC, shev7 requested changes

2024-05-27 06:13 UTC, shev7 commented on src/components/app/app.tsx
>  import { AppAPIProvider } from "../../graphql";
absolute import path

2024-05-27 06:13 UTC, shev7 commented on src/components/app/app.tsx
>  import { AppAPIProvider } from "../../graphql";
absolute import path

2024-05-27 06:13 UTC, shev7 commented on src/router/constants.ts
> +    positions: "/positions",
you can implement this like dynamic routing helpers
for example if route accepts userId as param it can be a function
(userId) => `/users/${userId}`
so this can be reused in both router setup and navigation

2024-05-27 06:13 UTC, shev7 commented on src/router/router.tsx
> +        <BrowserRouter>
use createBrowserRouter

2024-05-28 06:00 UTC, shev7 approved these changes

2024-05-28 06:00 UTC, shev7 commented on src/components/app/app.tsx
>  import { AppAPIProvider } from "../../graphql";
the same
use absolute import path

2024-05-28 07:44 UTC, AAKlimkov approved these changes

2024-05-29 11:59 UTC, savelievamareena approved these changes

2024-05-29 12:01 UTC, merged