feature/DEV-8-auth
savelievamareena/cv-final pull request #9
Opened 2024-05-29 18:05 UTC by RC-3222

Adds main authentication functionality (sign in/sign up/verification pages + route protection). 

Styles are still WIP, but, since the user authentication is required by any other data-requesting stuff (we need tokens for request headers), this may (probably) be reviewed/merged a bit earlier.

2024-05-30 07:28 UTC, shev7 requested changes

2024-05-30 07:28 UTC, shev7 commented on src/components/form-text-field/form-text-field.tsx
> +    }, []);
why do you need this for??
you can also use ```<Controller/>``` from react-hooks-form if you need on change

2024-05-30 07:28 UTC, shev7 commented on src/components/main-layout/main-layout.tsx
> +    const user = useReactiveVar(authService.user);
create hook for that in authService

2024-05-30 07:28 UTC, shev7 commented on src/modules/auth/components/login-form/login-form.tsx
> +        if (data) authService.login(data.login.user, data.login.access_token);
this can be done in onSuccess callback of use query or useMutation

2024-05-30 07:28 UTC, shev7 commented on src/modules/auth/components/login-form/login-form.tsx
> +        if (data) authService.login(data.login.user, data.login.access_token);
sorry, onCompleted, not onSuccess

2024-05-30 07:28 UTC, shev7 commented on src/modules/auth/components/auth-layout/auth-layout.module.scss
> +@use "../../../../scss" as *;
why do you need this for??
if you need some global styles, import in globally, no need to import it in every file

2024-05-30 07:28 UTC, shev7 commented on src/modules/auth/components/login-form/login-form.tsx
> +            <PasswordInput />
passwrod input should also accept props as text field above

2024-05-30 07:28 UTC, shev7 commented on src/modules/auth/components/password-input/password-input.tsx
> +            name='password'
this should be inherited from props of text field and passed on form level

2024-05-30 07:28 UTC, shev7 commented on src/modules/auth/components/password-input/password-input.tsx
> +    const EyeIcon = visible ? EyeFilled : EyeOutlined;
move this condition to jsx

2024-05-30 07:28 UTC, shev7 commented on src/modules/auth/components/password-input/password-input.tsx
> +                    }}
see if there is some icon button component in antd or create it yourself

2024-05-30 07:28 UTC, shev7 commented on src/modules/auth/components/sign-up-form/sign-up-form.tsx
> +import { routes } from "@/router";
please follow import order
react
libraries
others
styles

2024-05-30 07:28 UTC, shev7 commented on src/modules/auth/components/sign-up-form/sign-up-form.tsx
> +        if (data) authService.login(data.signup.user, data.signup.access_token);
this can also be done in onCompleted

2024-05-30 07:28 UTC, shev7 commented on src/modules/auth/components/sign-up-form/sign-up-form.tsx
> +    const [signUp] = useSignUp();
why are you not using loading, to handle loading states

2024-05-30 07:28 UTC, shev7 commented on src/modules/auth/components/verify-mail-form/verify-mail-form.tsx
> +                        authService.verify();
also can be moved to onCompleted

2024-05-30 07:28 UTC, shev7 commented on src/modules/auth/components/verify-mail-form/verify-mail-form.tsx
> +    const [verifyMail] = useVerifyMail();
handle loading state, attach loading to button disabled={loading}

2024-05-30 07:28 UTC, shev7 commented on src/modules/auth/schemas/login.ts
> +});
later translations need to be attached here

2024-05-30 07:28 UTC, shev7 commented on src/services/auth-service.ts
> +
import order

2024-05-30 07:28 UTC, shev7 commented on src/services/auth-service.ts
> +        localStorage.setItem(AUTH_TOKEN, accessToken);
create some kind of storage service

here is example:

```
import { IStorageService, StorageKey } from './Storage.types';

class StorageService implements IStorageService {
  constructor(private readonly storage: Storage) {}

  setItem<T>(key: StorageKey, item: T) {
    this.storage.setItem(key, JSON.stringify(item));
  }

  getItem<T>(key: StorageKey): T | null {
    const item = this.storage.getItem(key);
    if (item) {
      return JSON.parse(item);
    }
    return null;
  }

  removeItem(key: StorageKey) {
    this.storage.removeItem(key);
  }
}

export const localStorageService = new StorageService(localStorage);
export const sessionStorageService = new StorageService(sessionStorage);

```

2024-05-30 14:15 UTC, shev7 requested changes

2024-05-30 14:15 UTC, shev7 commented on src/components/form-text-field/form-text-field.tsx
> +            render={({ field: { value, onChange } }) => {
just spread field to  input

2024-05-30 14:15 UTC, shev7 commented on src/modules/auth/components/verify-mail-form/verify-mail-form.tsx
> +            schema={getVerifyMailFormSchema(t)}
this can be done like this, no need to path t to function
<img width="731" alt="image" src="https://github.com/savelievamareena/cv-final/assets/72657584/f0e1d286-91d8-49b4-ac2a-dec92f332775">

2024-05-30 14:15 UTC, shev7 commented on src/services/auth-service/auth-service.ts
> +export const authService = new AuthService(localStorageService);
dont' pass localStorage to constructor, just use it inside of your class methods

2024-05-30 15:46 UTC, shev7 commented on src/modules/auth/components/verify-mail-form/verify-mail-form.tsx
> +import { verifyMailFormSchema } from "../../schemas";
If language changes would it work as schema object in this case, I think this should be a function
Cause it will create schema on app start with initial language, and when language changed the schema won't be recreated
Check this moment please

2024-05-31 06:41 UTC, shev7 approved these changes
looks good, apply last small fixes and merge

2024-05-31 06:41 UTC, shev7 commented on package.json
> +        "sass": "^1.77.2",
remove sass from dependencies, it should only be presented in dev deps

2024-05-31 06:41 UTC, shev7 commented on src/components/form-text-field/form-text-field.tsx
> +/* eslint-disable @typescript-eslint/no-unsafe-assignment */
please avoid supressing linter

2024-05-31 06:41 UTC, shev7 commented on src/components/form/form.tsx
> +/* eslint-disable @typescript-eslint/no-misused-promises */
the same

2024-05-31 06:41 UTC, shev7 commented on src/modules/auth/components/password-input/password-input.tsx
> +    const [visible, setVisible] = useState(false);
isVisible

2024-05-31 06:41 UTC, shev7 commented on src/services/auth-service/auth-service.ts
> +import { USER, AUTH_TOKEN } from "@/constants";
might be good idea to create enum for Storage keys

2024-05-31 08:34 UTC, AAKlimkov commented on src/modules/auth/components/auth-layout/index.ts
do we need empty files?

2024-05-31 08:34 UTC, AAKlimkov commented on src/modules/auth/components/login-form/index.ts
same as above

2024-05-31 08:37 UTC, RC-3222 commented on src/modules/auth/components/auth-layout/index.ts
fixed

2024-05-31 12:09 UTC, savelievamareena approved these changes

2024-05-31 12:10 UTC, merged